In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import datetime as dt

In [3]:
df = pd.read_csv("../data/smart_logistics_dataset.csv")

In [4]:
df["Logistics_Delay"].isnull().sum()

np.int64(0)

In [5]:
# df['Logistics_Delay_Reason'] = df['Logistics_Delay_Reason'].fillna(df['Logistics_Delay_Reason'].mean())

In [6]:
df['Logistics_Delay_Reason'].isnull().sum()

np.int64(263)

In [7]:
df.isnull().sum()

Timestamp                    0
Asset_ID                     0
Latitude                     0
Longitude                    0
Inventory_Level              0
Shipment_Status              0
Temperature                  0
Humidity                     0
Traffic_Status               0
Waiting_Time                 0
User_Transaction_Amount      0
User_Purchase_Frequency      0
Logistics_Delay_Reason     263
Asset_Utilization            0
Demand_Forecast              0
Logistics_Delay              0
dtype: int64

In [8]:
df["Logistics_Delay_Reason"].value_counts()

Logistics_Delay_Reason
Weather               267
Traffic               236
Mechanical Failure    234
Name: count, dtype: int64

In [9]:
df["Logistics_Delay_Reason"] = df["Logistics_Delay_Reason"].replace(("None"),np.nan)

In [10]:
df["Logistics_Delay_Reason"] = df["Logistics_Delay_Reason"].fillna(df["Logistics_Delay_Reason"].mode()[0])

In [11]:
df["Logistics_Delay_Reason"].isnull().sum()

np.int64(0)

In [12]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [13]:
df["Year"] = df["Timestamp"].dt.year
df["Month"] = df["Timestamp"].dt.month
df["Day"] = df["Timestamp"].dt.day
df["Hour"] = df["Timestamp"].dt.hour
df["Day_of_Week"] = df["Timestamp"].dt.dayofweek

In [14]:
df.shape

(1000, 21)

In [15]:
df.drop("Timestamp", axis=1, inplace=True)

In [16]:
df.head()

,Asset_ID,Latitude,Longitude,Inventory_Level,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Logistics_Delay_Reason,Asset_Utilization,Demand_Forecast,Logistics_Delay,Year,Month,Day,Hour,Day_of_Week
0,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,Weather,60.1,285,1,2024,3,20,0,2
1,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1,2024,10,30,7,2
2,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,Weather,99.2,260,0,2024,7,29,18,0
3,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1,2024,10,28,0,0
4,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,Weather,71.6,270,1,2024,9,27,15,4

In [17]:
df.select_dtypes(include="object").columns

Index(['Asset_ID', 'Shipment_Status', 'Traffic_Status',
       'Logistics_Delay_Reason'],
      dtype='object')

In [18]:
for col in ["Asset_ID","Shipment_Status","Traffic_Status","Logistics_Delay_Reason"]:
    print(col)
    print(df[col].unique())
    print("-"*40)

Asset_ID
['Truck_7' 'Truck_6' 'Truck_10' 'Truck_9' 'Truck_4' 'Truck_2' 'Truck_8'
 'Truck_3' 'Truck_5' 'Truck_1']
----------------------------------------
Shipment_Status
['Delayed' 'In Transit' 'Delivered']
----------------------------------------
Traffic_Status
['Detour' 'Heavy' 'Clear']
----------------------------------------
Logistics_Delay_Reason
['Weather' 'Traffic' 'Mechanical Failure']
----------------------------------------

In [19]:
categorical_cols = [
    "Asset_ID",
    "Shipment_Status",
    "Traffic_Status",
    "Logistics_Delay_Reason"
]

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [20]:
df.shape

(1000, 31)

In [21]:
df.head()

,Latitude,Longitude,Inventory_Level,Temperature,Humidity,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Asset_Utilization,Demand_Forecast,...,Asset_ID_Truck_6,Asset_ID_Truck_7,Asset_ID_Truck_8,Asset_ID_Truck_9,Shipment_Status_Delivered,Shipment_Status_In Transit,Traffic_Status_Detour,Traffic_Status_Heavy,Logistics_Delay_Reason_Traffic,Logistics_Delay_Reason_Weather
0,-65.7383,11.2497,390,27.0,67.8,38,320,4,60.1,285,...,False,True,False,False,False,False,True,False,False,True
1,22.2748,-131.7086,491,22.5,54.3,16,439,7,80.9,174,...,True,False,False,False,False,True,False,True,False,True
2,54.9232,79.5455,190,25.2,62.2,34,355,3,99.2,260,...,False,False,False,False,False,True,True,False,False,True
3,42.3900,-1.4788,330,25.4,52.3,37,227,5,97.4,160,...,False,False,False,True,True,False,False,True,True,False
4,-65.8477,47.9468,480,20.5,57.2,56,197,6,71.6,270,...,False,True,False,False,False,False,False,False,False,True

In [22]:
asset_columns = [col for col in df.columns if col.startswith("Asset_ID_")]

df = df.drop(columns=asset_columns)

print(df.columns)

Index(['Latitude', 'Longitude', 'Inventory_Level', 'Temperature', 'Humidity',
       'Waiting_Time', 'User_Transaction_Amount', 'User_Purchase_Frequency',
       'Asset_Utilization', 'Demand_Forecast', 'Logistics_Delay', 'Year',
       'Month', 'Day', 'Hour', 'Day_of_Week', 'Shipment_Status_Delivered',
       'Shipment_Status_In Transit', 'Traffic_Status_Detour',
       'Traffic_Status_Heavy', 'Logistics_Delay_Reason_Traffic',
       'Logistics_Delay_Reason_Weather'],
      dtype='object')

In [24]:
df.to_csv("Processed_dataset.csv", index=False)